#!/usr/bin/env bash

# credit: http://blog.kfish.org/2010/04/git-lola.html
[alias]
        lol = log --graph --decorate --pretty=oneline --abbrev-commit
        lola = log --graph --decorate --pretty=oneline --abbrev-commit --all
[color]
        branch = auto
        diff = auto
        interactive = auto
        status = auto
[core]
        editor = nvim
